[tool.poetry]
name = "srcstudiomodel"
version = "0.4.0"
description = ""
authors = ["aoisensi <me@aoisensi.info>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
